### ISSUE TITLE
Dark Mode Single feed entries 

### ISSUE THREAD

**Issue by seanbperiod** [yamalight/feedly-colorful-list-view#1]
Thanks for the mag/card update! 

I also noticed that the single feed in dark mode doesn't appear to respond to the css in Title Only, Magazine, and Cards View. 

Either the background color or the title color should be updated, but I can't figure out how to isolate it without affecting other items. 

<img width="1423" alt="Screenshot 2023-01-13 at 2 40 29 PM" src="https://user-images.githubusercontent.com/8443498/212405701-ba623d4c-fafa-492e-9c57-9e181dd904e6.png">

Thanks!

**Comment by yamalight** [comment]
Ah, that's a tricky one. I'll try to solve it when I have time. Would be more than happy to merge a PR with fix though :)

**Comment by seanbperiod** [comment]
I think I found the fix: 

(It's been awhile since I've done PR reqs 😅)

 .theme--dark .fx .entry { background: rgb(255 255 255 / 88%);
