### ISSUE TITLE
When one article is selected, it is not color coded.

### ISSUE THREAD

**Issue by urotan1003** [yamalight/feedly-colorful-list-view#4]
Thanks for publishing the script. I always make use of it.

As shown in the image, when one article is selected, it is not color coded. Is there anyway to adjust?
![241030](https://github.com/user-attachments/assets/566a3e76-fef9-4d88-a5e3-9075a72cdc81)

**Comment by yamalight** [comment]
This is intentional as there are no sources to distinguish between 🤔

**Comment by yamalight** [comment]
Will close this, feel free to reopen if something is not clear.
